# -*- coding: utf-8 -*-
"""ResNet-152.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofBGpVxBT_eN0KFs3-071ZqQ6ARKi6cb
"""

import tensorflow as tf
from tensorflow.keras import layers, models, Model

def VGG19_Model(input_shape=(224, 224, 3), classes=1000):
    inputs = layers.Input(shape=input_shape, name='input_layer')

    # Block 1
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same', name='conv1_1')(inputs)
    x = layers.Conv2D(64, (3, 3), activation='relu', padding='same', name='conv1_2')(x)
    x = layers.MaxPooling2D((2, 2), strides=(2, 2), name='pool1')(x)

    # Block 2
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same', name='conv2_1')(x)
    x = layers.Conv2D(128, (3, 3), activation='relu', padding='same', name='conv2_2')(x)
    x = layers.MaxPooling2D((2, 2), strides=(2, 2), name='pool2')(x)

    # Block 3
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv3_1')(x)
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv3_2')(x)
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv3_3')(x)
    x = layers.Conv2D(256, (3, 3), activation='relu', padding='same', name='conv3_4')(x)
    x = layers.MaxPooling2D((2, 2), strides=(2, 2), name='pool3')(x)

    # Block 4
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv4_1')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv4_2')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv4_3')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv4_4')(x)
    x = layers.MaxPooling2D((2, 2), strides=(2, 2), name='pool4')(x)

    # Block 5
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv5_1')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv5_2')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv5_3')(x)
    x = layers.Conv2D(512, (3, 3), activation='relu', padding='same', name='conv5_4')(x)
    x = layers.MaxPooling2D((2, 2), strides=(2, 2), name='pool5')(x)

    # Fully Connected Layers
    x = layers.Flatten(name='flatten')(x)
    x = layers.Dense(4096, activation='relu', name='fc1')(x)
    x = layers.Dense(4096, activation='relu', name='fc2')(x)
    outputs = layers.Dense(classes, activation='softmax', name='predictions')(x)

    model = Model(inputs=inputs, outputs=outputs, name="VGG19")
    return model

# Build the model
model = VGG19_Model(input_shape=(224, 224, 3), classes=1000)

# Generate architecture summary
model.summary()

import tensorflow as tf
from tensorflow.keras import layers, Model

# ---------------------------------------------------
# Identity Block
# ---------------------------------------------------
def identity_block(x, filters, kernel_size=3):
    f1, f2, f3 = filters
    shortcut = x

    x = layers.Conv2D(f1, (1, 1), strides=(1, 1), padding='valid')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)

    x = layers.Conv2D(f2, (kernel_size, kernel_size), strides=(1, 1), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)

    x = layers.Conv2D(f3, (1, 1), strides=(1, 1), padding='valid')(x)
    x = layers.BatchNormalization()(x)

    x = layers.Add()([x, shortcut])
    x = layers.Activation('relu')(x)

    return x


# ---------------------------------------------------
# Convolutional Block
# Used when dimensions need to change
# ---------------------------------------------------
def conv_block(x, filters, stride=2, kernel_size=3):
    f1, f2, f3 = filters
    shortcut = x

    x = layers.Conv2D(f1, (1, 1), strides=(stride, stride), padding='valid')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)

    x = layers.Conv2D(f2, (kernel_size, kernel_size), strides=(1, 1), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)

    x = layers.Conv2D(f3, (1, 1), strides=(1, 1), padding='valid')(x)
    x = layers.BatchNormalization()(x)

    shortcut = layers.Conv2D(f3, (1, 1), strides=(stride, stride), padding='valid')(shortcut)
    shortcut = layers.BatchNormalization()(shortcut)

    x = layers.Add()([x, shortcut])
    x = layers.Activation('relu')(x)

    return x


# ---------------------------------------------------
# ResNet-152 Model
# Block distribution = [3, 8, 36, 3]
# ---------------------------------------------------
def ResNet152(input_shape=(224, 224, 3), classes=1000):
    inputs = layers.Input(shape=input_shape)

    # Initial layers
    x = layers.ZeroPadding2D((3, 3))(inputs)
    x = layers.Conv2D(64, (7, 7), strides=(2, 2), padding='valid')(x)
    x = layers.BatchNormalization()(x)
    x = layers.Activation('relu')(x)
    x = layers.ZeroPadding2D((1, 1))(x)
    x = layers.MaxPooling2D((3, 3), strides=(2, 2))(x)

    # Stage 2 -> 3 blocks
    x = conv_block(x, [64, 64, 256], stride=1)
    for _ in range(2):
        x = identity_block(x, [64, 64, 256])

    # Stage 3 -> 8 blocks
    x = conv_block(x, [128, 128, 512], stride=2)
    for _ in range(7):
        x = identity_block(x, [128, 128, 512])

    # Stage 4 -> 36 blocks
    x = conv_block(x, [256, 256, 1024], stride=2)
    for _ in range(35):
        x = identity_block(x, [256, 256, 1024])

    # Stage 5 -> 3 blocks
    x = conv_block(x, [512, 512, 2048], stride=2)
    for _ in range(2):
        x = identity_block(x, [512, 512, 2048])

    # Final layers
    x = layers.GlobalAveragePooling2D()(x)
    outputs = layers.Dense(classes, activation='softmax')(x)

    model = Model(inputs, outputs, name='ResNet152')
    return model


# ---------------------------------------------------
# Build and show model
# ---------------------------------------------------
model = ResNet152(input_shape=(224, 224, 3), classes=1000)
model.summary()

import torch
import torchvision.transforms as transforms
import torchvision.models as models
import torchvision.datasets as datasets
from torch.utils.data import DataLoader, Subset
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np

# Device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load pretrained ResNet-152
model = models.resnet152(pretrained=True)
model = model.to(device)
model.eval()

# ImageNet normalization
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# Example dataset: CIFAR-10
dataset = datasets.CIFAR10(root="./data", train=False, download=True, transform=transform)

# Take first 10 images
subset = Subset(dataset, range(10))
loader = DataLoader(subset, batch_size=1, shuffle=False)

# CIFAR-10 class names
cifar10_classes = dataset.classes

# Download ImageNet class labels if not already present
import os
if not os.path.exists("imagenet_classes.txt"):
    !wget -nc https://raw.githubusercontent.com/pytorch/hub/master/imagenet_classes.txt

# Load ImageNet class labels
with open("imagenet_classes.txt", "r") as f:
    imagenet_classes = [line.strip() for line in f.readlines()]

# Optional: ImageNet labels
predictions = []

# Helper transform for showing original image
display_transform = transforms.Compose([
    transforms.Resize((224, 224))
])

fig, axes = plt.subplots(2, 5, figsize=(15, 6))

with torch.no_grad():
    for i, (image, true_label) in enumerate(loader):
        image = image.to(device)
        output = model(image)
        _, predicted = torch.max(output, 1)

        predictions.append((i, true_label.item(), predicted.item()))

        # Convert image for display
        img_np = image[0].cpu().numpy().transpose(1, 2, 0)
        img_np = np.array([0.229, 0.224, 0.225]) * img_np + np.array([0.485, 0.456, 0.406])
        img_np = np.clip(img_np, 0, 1)

        ax = axes[i // 5, i % 5]
        ax.imshow(img_np)
        ax.set_title(f"True: {cifar10_classes[true_label.item()]}\nPred: {imagenet_classes[predicted.item()]}")
        ax.axis("off")

plt.tight_layout()
plt.show()

# Print predictions
for idx, true_lbl, pred_lbl in predictions:
    print(f"Image {idx+1}: True Label = {cifar10_classes[true_lbl]}, Predicted Label = {imagenet_classes[pred_lbl]}")